[package]
name = "mairie360_api_lib"
version = "0.1.0"
authors = ["Quentin TENNEREL <quentin.tennerel@epitech.eu>"]
edition = "2021"
description = "Lib for mairie360 APIs"
license = "MIT"
repository = "https://github.com/mairie360/API_lib"

[dependencies]
actix-web = "4"
jsonwebtoken = "9.3.1"
once_cell = "1.21.3"
serde = { version = "1.0.219", features = ["derive"] }

