[package]
name = "mairie360_api_lib"
version = "0.1.0"
authors = ["Quentin TENNEREL <quentin.tennerel@epitech.eu>"]
edition = "2021"
description = "Lib for mairie360 APIs"
license = "MIT"
repository = "https://github.com/mairie360/API_lib"

[dependencies]
async-trait = "0.1.89"
once_cell = "1.21.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.46.0", features = ["full"] }
tokio-postgres = { version = "0.7", features = ["with-uuid-1"] }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
testcontainers = "0.26.2"
postgres = "0.19"
