[package]
name = "mairie360_api_lib"
version = "0.1.2"
authors = ["Quentin TENNEREL <quentin.tennerel@epitech.eu>"]
edition = "2021"
description = "Lib for mairie360 APIs"
license = "MIT"
repository = "https://github.com/mairie360/API_lib"

[dependencies]
once_cell = "1.21.3"
redis = "1.0.3"
tokio = { version = "1.49.0", features = ["full"] }

[dev-dependencies]
serial_test = "3.3.1"
temp-env = "0.3.6"
testcontainers = "0.27.0"
tokio = { version = "1.49.0", features = ["full"] }
