[package]
name = "mairie360_api_lib"
version = "0.2.0"
authors = ["Quentin TENNEREL <quentin.tennerel@epitech.eu>"]
edition = "2021"
description = "Lib for mairie360 APIs"
license = "MIT"
repository = "https://github.com/mairie360/API_lib"

[dependencies]
once_cell = "1.21.3"
redis = "0.32.3"
tokio = { version = "1.46.0", features = ["full"] }

[dev-dependencies]
testcontainers = "0.15"
tokio = { version = "1", features = ["full"] }
