[version]
major_version_zero = false

[[commit_types]]
type = "feat"
bump = "minor"

[[commit_types]]
type = "fix"
bump = "patch"

[[commit_types]]
type = "major"
bump = "major"

[parser]
breaking_change_indicators = ["!"]