name: API-Lib-CI/CD

on:
  push:
  workflow_dispatch:
    main

jobs:
  CICD:
    uses: mairie360/CICD/.github/workflows/back-lib-cicd.yml@feat/MAIR-5-add-api-lib-cicd
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.inherit }}
